version: 0.2

phases:

  pre_build:
    commands:
      - echo Installing Dependencies

  build:
    commands:
      - echo Building and Tagging Docker Image
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 369435385236.dkr.ecr.ap-south-1.amazonaws.com
      - docker build -t community-app .
      - docker tag community-app:latest 369435385236.dkr.ecr.ap-south-1.amazonaws.com/community-app:latest

  post_build:
    commands:
      - echo Pushing to ECR
      - docker push 369435385236.dkr.ecr.ap-south-1.amazonaws.com/community-app:latest
      - printf '[{"name":"community-app","imageUri":"369435385236.dkr.ecr.ap-south-1.amazonaws.com/community-app:latest"}]' > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
